### PR TITLE
Update project and entity details

### PR DESCRIPTION
**Pull request by swinslow**
Signed-off-by: Steve Winslow <steve@swinslow.net>

### CODE REVIEW

**Comment by maoo** [comment]
**IMPORTANT!** @nicoalba - please merge first #2 and follow the instructions there; we can use this Pull Request to check if the preview website is updated. Thank you!

**Comment by brooklynrob** [comment]
The source of this conflict is, at least in part, that @nicoalba's latest version of this repo no longer has a /docs/get-involved folder -- looks like Nico has moved terms-of-service.md to the /docs/getting-started folder.

One way to resolved this would like me to resolve the conflict as described above at the command line, which will result in a temporary "new" /docs/get-involved folder and to then do a `git mv` of the file, also at the command prompt, into the /docs/getting-started folder. 

CC @swinslow @maoo @aitana16

**Comment by nicoalba** [comment]
@brooklynrob Yeah, I combined the .md files into one folder as I didn't see a reason to do otherwise, but of course either way works for me.

**Comment by brooklynrob** [comment]
> @brooklynrob Yeah, I combined the .md files into one folder as I didn't see a reason to do otherwise, but of course either way works for me.

Yeah, that's fine (note if we want to leave it with just having everything in a a single folder we might at some point want to move all the files up one level into the /docs folder rather than have an extraneous extra single sub-folder) -- you'll just need to do a `git mv` after merging in @swinslow's updates to the terms of service file to move that into /doc/getting-started

**Comment by maoo** [comment]
Closing this PR. @swinslow , could you please try to apply your changes on a branch that is updated with the current master version? TY!

**Pull request closed without merging**
